name: Docker

on: [push]

jobs:
    build-and-test-package:
        name: Build & Test Package
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Build (typecheck) the project
              run: npm run build
            - name: Lint the project
              run: npm run lint
            - name: Test the project
              run: npm run coverage
